DB_URL=jdbc:postgresql://ep-broad-rice-am6kaoj3-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
DB_USERNAME=neondb_owner
DB_PASSWORD=npg_lqQVwPWLx4u6
GROQ_API_KEY=sk_ZX0FeY2z1nydFS8GdltgWGdyb3FYdz0RILCOUQeSDPBMzXm2YTaO